// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXc35vI6pChoG8pYrtawFUbFoPzpdtuKI',
    appId: '1:525276198741:web:29173e4db034f0959d21dc',
    messagingSenderId: '525276198741',
    projectId: 'med-connect-36e65',
    authDomain: 'med-connect-36e65.firebaseapp.com',
    storageBucket: 'med-connect-36e65.firebasestorage.app',
    measurementId: 'G-XH2Z8K2RM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAofSaOP7AgVMFFbjmXGqb0wovKmOb8FvM',
    appId: '1:525276198741:android:7aae3fb0a75ba0a29d21dc',
    messagingSenderId: '525276198741',
    projectId: 'med-connect-36e65',
    storageBucket: 'med-connect-36e65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBN0In7wo-mofCFKrl3viHo__hbk8OQCc',
    appId: '1:525276198741:ios:d924138a7874d4109d21dc',
    messagingSenderId: '525276198741',
    projectId: 'med-connect-36e65',
    storageBucket: 'med-connect-36e65.firebasestorage.app',
    iosBundleId: 'com.example.medConnect',
  );
}
